apiVersion: v1
kind: Service
metadata:
  name: nginx-service-domain-2
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    name: nginx
