---
- name: Authentication cluster
  shell: pcs cluster auth -u {{ pcs_user }} -p {{ pcs_password }} --force

- name: Configure PCS
  shell: pcs cluster setup --name {{ pcs_cluster_name }} {{ pcs_master1 }} {{ pcs_master2 }} -u {{ pcs_user }} -p {{ pcs_password }} --force

- name: Initialize the cluster
  shell: pcs cluster start --all

- name: Enable the cluster
  shell: pcs cluster enable --all

- name: disable stonith
  shell: pcs property set stonith-enabled=false

- name: Add cluster resource with fixed IP PCS resources
  shell: pcs resource create ClusterIP ocf:heartbeat:IPaddr2 ip={{ pcs_masters_vip_address }} cidr_netmask={{ pcs_masters_vip_netmask }} nic={{ pcs_masters_nic }} op monitor interval={{ pcs_masters_interval }}

- name: Clone resource to be in both nodes
  shell: pcs resource clone ClusterIP globally-unique=true clone-max={{ pcs_masters_clone_max }} clone-node-max={{ pcs_masters_clone_node_max }}

- name: Create APIserver - PCS controller
  shell: pcs resource create APIServer systemd:kube-apiserver master-max={{ pcs_masters_master_max }} --group {{ pcs_masters_cluster_group_name }}

- name: Create scheduller - PCS controller
  shell: pcs resource create Scheduler systemd:kube-scheduler master-max={{ pcs_masters_master_max }} --group {{ pcs_masters_cluster_group_name }}

- name:  Create Kubernetes controller - PCS controller
  shell: pcs resource create Controller systemd:kube-controller-manager master-max={{ pcs_masters_master_max }} --group {{ pcs_masters_cluster_group_name }}

- name: Clone the PCS resources
  shell: pcs resource clone {{ pcs_masters_cluster_group_name }}

